services:
    web:
        depends_on:
            - api
        image: zvdcm/hanpoom-web
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        ports:
            - 3000:3000
        develop:
            watch:
                - path: './apps/web/package.json'
                  action: rebuild
                - path: './apps/web/package-lock.json'
                  action: rebuild
                - path: './apps/web'
                  target: '/app'
                  action: 'sync'
    api:
        depends_on:
            - db
        image: zvdcm/hanpoom-api
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        ports:
            - 3001:3001
        develop:
            watch:
                - path: './apps/api/package.json'
                  action: rebuild
                - path: './apps/api/package-lock.json'
                  action: rebuild
                - path: './apps/api'
                  target: '/app'
                  action: 'sync'
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_DB: hanpoom
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root123

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
