import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import TanstackQueryClientProvider from '@/components/providers/tanstack-query-client-provider';
import { Toaster } from 'sonner';
import AuthProvider from '@/components/providers/auth-provider';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    auth,
    home,
}: Readonly<{
    children: React.ReactNode;
    auth: React.ReactNode;
    home: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <TanstackQueryClientProvider>
                    <AuthProvider {...{ auth, home }}>{children}</AuthProvider>
                </TanstackQueryClientProvider>
                <Toaster />
            </body>
        </html>
    );
}
